/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.Enfoques_probabilidad_p;

import Forms.Main_window;

/**
 *
 * @author cuitlahuac
 */
public class Enfoques_probabilidad extends javax.swing.JFrame {

    /**
     * Creates new form Enfoques_probabilidad
     */
    public Enfoques_probabilidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_interpretacion = new javax.swing.JButton();
        b_condicional = new javax.swing.JButton();
        b_adicion = new javax.swing.JButton();
        b_total = new javax.swing.JButton();
        b_bayes = new javax.swing.JButton();
        b_regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b_interpretacion.setText("Interpretacion de probabilidades");
        b_interpretacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_interpretacionActionPerformed(evt);
            }
        });

        b_condicional.setText("Probabilidad condicional");
        b_condicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_condicionalActionPerformed(evt);
            }
        });

        b_adicion.setText("Regla general de adicion");
        b_adicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_adicionActionPerformed(evt);
            }
        });

        b_total.setText("Probabilidad total");
        b_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_totalActionPerformed(evt);
            }
        });

        b_bayes.setText("Teorema de Bayes");
        b_bayes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_bayesActionPerformed(evt);
            }
        });

        b_regresar.setText("Regresar");
        b_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_regresarActionPerformed(evt);
            }
        });

        jLabel1.setText("Enfoques de probabilidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(b_regresar)
                            .addComponent(b_interpretacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_condicional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_adicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_bayes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(b_interpretacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_condicional)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_adicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_bayes)
                .addGap(18, 18, 18)
                .addComponent(b_regresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_adicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_adicionActionPerformed
        this.setVisible(false);
        Adicion adicion = new Adicion();
        adicion.setVisible(true);
    }//GEN-LAST:event_b_adicionActionPerformed

    private void b_interpretacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_interpretacionActionPerformed
        this.setVisible(false);
        Interpretacion interpretacion = new Interpretacion();
        interpretacion.setVisible(true);
    }//GEN-LAST:event_b_interpretacionActionPerformed

    private void b_condicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_condicionalActionPerformed
       this.setVisible(false);
        Condicional condicional = new Condicional();
        condicional.setVisible(true);
    }//GEN-LAST:event_b_condicionalActionPerformed

    private void b_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_regresarActionPerformed
        this.setVisible(false);
        Main_window main = new Main_window();
        main.setVisible(true);
    }//GEN-LAST:event_b_regresarActionPerformed

    private void b_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_totalActionPerformed
        this.setVisible(false);
        Total total = new Total();
        total.setVisible(true);
    }//GEN-LAST:event_b_totalActionPerformed

    private void b_bayesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_bayesActionPerformed
        this.setVisible(false);
        Bayes bayes = new Bayes();
        bayes.setVisible(true);
    }//GEN-LAST:event_b_bayesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enfoques_probabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enfoques_probabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enfoques_probabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enfoques_probabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enfoques_probabilidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_adicion;
    private javax.swing.JButton b_bayes;
    private javax.swing.JButton b_condicional;
    private javax.swing.JButton b_interpretacion;
    private javax.swing.JButton b_regresar;
    private javax.swing.JButton b_total;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
