/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.Estadistica_descriptiva_p;

import java.util.Arrays;

/**
 *
 * @author cuitlahuac
 */
public class Tendencia_central extends javax.swing.JFrame {

    /**
     * Creates new form Tendencia_central
     */
    public Tendencia_central() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_moda = new javax.swing.JButton();
        b_mediana = new javax.swing.JButton();
        b_media = new javax.swing.JButton();
        b_regresar = new javax.swing.JButton();
        txt_elementos = new javax.swing.JTextField();
        list1 = new java.awt.List();
        l_resultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        b_limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b_moda.setText("Moda");
        b_moda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_modaActionPerformed(evt);
            }
        });

        b_mediana.setText("Mediana");
        b_mediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_medianaActionPerformed(evt);
            }
        });

        b_media.setText("Media");
        b_media.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_mediaActionPerformed(evt);
            }
        });

        b_regresar.setText("Regresar");
        b_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_regresarActionPerformed(evt);
            }
        });

        jLabel1.setText("Resultado");

        jLabel2.setText("Ingresar los valores separados por una coma \",\"");

        b_limpiar.setText("Limpiar");
        b_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b_media, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(b_moda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(b_mediana, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(l_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                                .addComponent(b_limpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_regresar)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_elementos, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_elementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_moda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_mediana)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_media)
                                .addGap(35, 83, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b_regresar)
                                    .addComponent(b_limpiar)))))
                    .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_modaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_modaActionPerformed
        l_resultado.setText("");
        //Obtener datos del textbox en arreglo
        String dato = (txt_elementos.getText());
        //Guardar arreglo en list
        list1.removeAll();
        String[] parts = dato.split(",");
        for (String part : parts) {
            list1.add(part);
        }
        //Creacion de arreglo tipo int
        int[] array_enteros = new int[parts.length]; 
        //Pasar de String a int
        for (int i = 0; i < array_enteros.length; i++){
            array_enteros[i] = Integer.parseInt(parts[i]);
        }
        //Acomodo de menor a mayor
        int temporal = 0;

        for (int i = 0; i < array_enteros.length; i++) {
            for (int j = 1; j < (array_enteros.length - i); j++) {
                if (array_enteros[j - 1] > array_enteros[j]) {
                    temporal = array_enteros[j - 1];
                    array_enteros[j - 1] = array_enteros[j];
                    array_enteros[j] = temporal;
                }
            }
        }
        //Calculo de la moda
        int i,j,frecTemp, frecModa = 0, moda1 = -1;
        for ( i = 0; i < array_enteros.length; i++ ) {
            frecTemp = 1; 
            for ( j = i + 1; j < array_enteros.length; j++ ) {
              if ( array_enteros [ i ] == array_enteros [ j ] )
                frecTemp++;
            }
            if ( frecTemp > frecModa ) {
              frecModa = frecTemp;
              moda1 = array_enteros [ i ];
      }
    }
        l_resultado.setText(Integer.toString(moda1));
    }//GEN-LAST:event_b_modaActionPerformed

    private void b_medianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_medianaActionPerformed
        l_resultado.setText("");
        //Obtener datos del textbox en arreglo
        String dato = (txt_elementos.getText());
        //Guardar arreglo en list
        list1.removeAll();
        String[] parts = dato.split(",");
        for (String part : parts) {
            list1.add(part);
        }
        //Creacion de arreglo tipo int
        int[] array_enteros = new int[parts.length]; 
        //Pasar de String a int
        for (int i = 0; i < array_enteros.length; i++){
            array_enteros[i] = Integer.parseInt(parts[i]);
        }
        //Acomodo de menor a mayor
        int temporal = 0;

        for (int i = 0; i < array_enteros.length; i++) {
            for (int j = 1; j < (array_enteros.length - i); j++) {
                if (array_enteros[j - 1] > array_enteros[j]) {
                    temporal = array_enteros[j - 1];
                    array_enteros[j - 1] = array_enteros[j];
                    array_enteros[j] = temporal;
                }
            }
        }
        //Calculo de la mediana
        int pos = 0, n = array_enteros.length,selector = 0;
        int temp = 0; 
        double temp0 = 0;    
        
        temp = n / 2;
        if ( n % 2 == 0 ) { //si es par
          temp0 = array_enteros[temp] + array_enteros[temp - 1];
          temp0 = temp0 / 2;
        }
        if ( n % 2 ==1 ) {//si es impar
          pos = (int)(temp + 0.5);
          temp0 = (array_enteros [ pos ]);  
        }

        l_resultado.setText(Double.toString(temp0));
    }//GEN-LAST:event_b_medianaActionPerformed

    private void b_mediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_mediaActionPerformed
        l_resultado.setText("");
        int i;
        float suma=0,resultado=0;
        String dato = (txt_elementos.getText());
        list1.removeAll();
        String[] parts = dato.split(",");
        for(i=0;i<parts.length;i++){
            list1.add(parts[i]);
        }
        for(i=0;i<parts.length;i++){
            suma = suma + Integer.parseInt(parts[i]);
        }
        resultado = suma / parts.length;
        l_resultado.setText(Float.toString(resultado));
    }//GEN-LAST:event_b_mediaActionPerformed

    private void b_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_regresarActionPerformed
        this.setVisible(false);
        Estadistica_descriptiva estadistica = new Estadistica_descriptiva();
        estadistica.setVisible(true);
    }//GEN-LAST:event_b_regresarActionPerformed

    private void b_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_limpiarActionPerformed
        txt_elementos.setText("");
        list1.removeAll();
        l_resultado.setText("");
        txt_elementos.requestFocus();
    }//GEN-LAST:event_b_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tendencia_central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tendencia_central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tendencia_central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tendencia_central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tendencia_central().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_limpiar;
    private javax.swing.JButton b_media;
    private javax.swing.JButton b_mediana;
    private javax.swing.JButton b_moda;
    private javax.swing.JButton b_regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l_resultado;
    private java.awt.List list1;
    private javax.swing.JTextField txt_elementos;
    // End of variables declaration//GEN-END:variables
}
